version = 1

test_patterns = ["spec/**"]

exclude_patterns = [
    "vendor/**",
    "log/**",
    "tmp/**",
    "public/**"
]

[[analyzers]]
name = "ruby"
enabled = true

  [analyzers.meta]
  plugin = "rubocop"